### ISSUE TITLE
Adopting GPLv3 License

### ISSUE THREAD

**Issue by nawtrey** [nawtrey/benzene#1]
I want to update the license to the GPLv3. I would take a look at what this license allows for [here](https://choosealicense.com/licenses/lgpl-3.0/) and make sure you are comfortable with it. The main reason to license it is that it gives other people the ability to use it legally, as long as they follow the guidelines in the license. Without a license there is no legal way for others to use our code.

Just respond with a "yes" if you're okay with adopting a new license.

**Comment by rsexton2** [comment]
yes

**Comment by jgens** [comment]
yes

**Comment by nawtrey** [comment]
yes

**Comment by nawtrey** [comment]
Since all original code contributors are in agreement, I'll go ahead and update the license to GPLv3 and close this issue.
